import React, { useState } from 'react';
import {
  BarChart3,
  TrendingUp,
  ShieldCheck,
  Search,
  CheckCircle2,
  XCircle,
  ExternalLink,
  Award,
  Zap,
  Filter,
} from 'lucide-react';
import { HistoricalPrediction } from '../types';

interface HistoricalAccuracyProps {
  history: HistoricalPrediction[];
}

export const HistoricalAccuracy: React.FC<HistoricalAccuracyProps> = ({ history }) => {
  const [filterResult, setFilterResult] = useState<'ALL' | 'WIN' | 'LOSS'>('ALL');
  const [filterMinConfidence, setFilterMinConfidence] = useState<number>(0);
  const [searchTerm, setSearchTerm] = useState<string>('');

  // Calculate High-Level Metrics
  const totalPredictions = history.length;
  const wins = history.filter((h) => h.result === 'WIN').length;
  const winRate = totalPredictions > 0 ? Math.round((wins / totalPredictions) * 1000) / 10 : 0;
  const totalPnl = history.reduce((sum, h) => sum + h.pnlPct, 0);
  const avgConfidence =
    totalPredictions > 0
      ? Math.round((history.reduce((sum, h) => sum + h.confidence, 0) / totalPredictions) * 10) / 10
      : 0;

  // Filter List
  const filteredHistory = history.filter((item) => {
    if (filterResult !== 'ALL' && item.result !== filterResult) return false;
    if (item.confidence < filterMinConfidence) return false;
    if (
      searchTerm &&
      !item.id.toLowerCase().includes(searchTerm.toLowerCase()) &&
      !item.hash.toLowerCase().includes(searchTerm.toLowerCase())
    ) {
      return false;
    }
    return true;
  });

  return (
    <div className="space-y-6 font-mono text-purple-100">
      {/* Header Banner */}
      <div className="bg-[#120B28] rounded-2xl border border-purple-500/30 p-6 shadow-xl relative overflow-hidden">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="px-2.5 py-0.5 rounded bg-purple-500/20 text-purple-300 border border-purple-500/30 text-xs font-mono font-bold flex items-center gap-1.5">
                <ShieldCheck className="w-4 h-4 text-purple-400" />
                VERIFIED PROOF OF ALPHA
              </span>
              <span className="text-purple-300/60 text-xs font-mono">100% On-Chain Non-Repudiation</span>
            </div>
            <h2 className="text-2xl font-black text-white font-mono tracking-tight">
              Historical Accuracy & Brier Score Analytics
            </h2>
            <p className="text-purple-300/70 text-xs mt-1 font-sans">
              Transparent, immutable log of every 15-minute Bitcoin prediction generated by VIXY'S VAULT decision intelligence models.
            </p>
          </div>

          <div className="flex items-center gap-2 bg-[#0B061A] px-4 py-2.5 rounded-xl border border-purple-900/40 font-mono text-xs text-purple-200">
            <Award className="w-5 h-5 text-purple-400" />
            <div>
              <span className="text-purple-300/60 text-[10px] block">Verified Streak</span>
              <span className="text-purple-300 font-bold">12 Consecutive Wins</span>
            </div>
          </div>
        </div>

        {/* Core Performance Summary Cards */}
        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-3 mt-6">
          <div className="bg-[#0B061A] p-4 rounded-xl border border-purple-900/40 space-y-1">
            <span className="text-purple-300/60 text-xs font-mono block">Overall Win Rate</span>
            <div className="font-mono font-black text-2xl text-emerald-400">{winRate}%</div>
            <span className="text-[10px] text-purple-300/50 font-mono block">{wins} Wins / {totalPredictions - wins} Losses</span>
            <span className="text-[9px] text-emerald-300/80 font-mono">Sample: n=340 (30 Days)</span>
          </div>

          <div className="bg-[#0B061A] p-4 rounded-xl border border-purple-900/40 space-y-1">
            <span className="text-purple-300/60 text-xs font-mono block">Realized vs Pred. Edge</span>
            <div className="font-mono font-black text-2xl text-cyan-300">+11.4%</div>
            <span className="text-[10px] text-purple-300/50 font-mono block">Predicted Avg: +12.2%</span>
            <span className="text-[9px] text-cyan-400 font-mono">Calibration Error: 0.8%</span>
          </div>

          <div className="bg-[#0B061A] p-4 rounded-xl border border-purple-900/40 space-y-1">
            <span className="text-purple-300/60 text-xs font-mono block">Cumulative Return</span>
            <div className="font-mono font-black text-2xl text-emerald-400">+{totalPnl.toFixed(1)}%</div>
            <span className="text-[10px] text-purple-300/50 font-mono block">Unleveraged YES/NO</span>
            <span className="text-[9px] text-purple-300/60 font-mono">Max DD: -3.8%</span>
          </div>

          <div className="bg-[#0B061A] p-4 rounded-xl border border-purple-900/40 space-y-1">
            <span className="text-purple-300/60 text-xs font-mono block">Avg Signal Confidence</span>
            <div className="font-mono font-black text-2xl text-purple-200">{avgConfidence}%</div>
            <span className="text-[10px] text-purple-300/50 font-mono block">Brier Score: 0.114</span>
            <span className="text-[9px] text-purple-300/60 font-mono">Calibrated Model</span>
          </div>

          <div className="bg-[#0B061A] p-4 rounded-xl border border-purple-900/40 space-y-1 col-span-2 md:col-span-1">
            <span className="text-purple-300/60 text-xs font-mono block">Honest Risk Diagnostics</span>
            <div className="font-mono font-black text-lg text-amber-300">2 Loss Streak (Max)</div>
            <span className="text-[10px] text-purple-300/50 font-mono block">Longest Win Streak: 12</span>
            <span className="text-[9px] text-amber-400/80 font-mono">No cherry-picked periods</span>
          </div>
        </div>

        {/* Breakdown Matrix by Timeframe & Asset */}
        <div className="mt-6 pt-5 border-t border-purple-900/40">
          <span className="text-xs font-bold text-white uppercase tracking-wider block mb-3">
            Rolling Win Rate Matrix By Timeframe & Asset (Last 300 Signals)
          </span>
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2.5 font-mono text-xs">
            {[
              { asset: 'BTC (15M)', rate: '82.4%', sample: 'n=142', edge: '+12.1%' },
              { asset: 'BTC (15S)', rate: '76.8%', sample: 'n=88', edge: '+9.4%' },
              { asset: 'ETH (15M)', rate: '84.1%', sample: 'n=95', edge: '+14.2%' },
              { asset: 'SOL (15M)', rate: '88.5%', sample: 'n=62', edge: '+16.8%' },
              { asset: 'XRP (15M)', rate: '74.2%', sample: 'n=40', edge: '+6.5%' },
              { asset: 'DOGE (15S)', rate: '72.1%', sample: 'n=53', edge: '+8.2%' },
            ].map((card, i) => (
              <div key={i} className="p-2.5 rounded-xl bg-[#080413] border border-purple-900/50 space-y-0.5">
                <div className="text-[10px] text-purple-300/60 font-bold">{card.asset}</div>
                <div className="text-base font-black text-emerald-400">{card.rate}</div>
                <div className="text-[9px] text-purple-300/50 flex justify-between">
                  <span>{card.sample}</span>
                  <span className="text-cyan-300">{card.edge}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Filter Toolbar */}
      <div className="bg-[#120B28] p-4 rounded-2xl border border-purple-900/40 flex flex-wrap items-center justify-between gap-4 font-mono text-xs">
        {/* Search Bar */}
        <div className="relative flex-1 min-w-[220px]">
          <Search className="w-4 h-4 text-purple-300/50 absolute left-3 top-2.5" />
          <input
            type="text"
            placeholder="Search by Signal ID or SHA-256 Hash..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full bg-[#0B061A] border border-purple-900/60 rounded-xl pl-9 pr-3 py-2 text-purple-100 placeholder-purple-300/40 focus:outline-none focus:border-purple-500/50"
          />
        </div>

        {/* Result Tabs */}
        <div className="flex items-center gap-1 bg-[#0B061A] p-1 rounded-xl border border-purple-900/40">
          <button
            onClick={() => setFilterResult('ALL')}
            className={`px-3 py-1 rounded-lg transition-all ${
              filterResult === 'ALL' ? 'bg-purple-600 text-white font-bold' : 'text-purple-300/60 hover:text-purple-200'
            }`}
          >
            All Signals ({history.length})
          </button>
          <button
            onClick={() => setFilterResult('WIN')}
            className={`px-3 py-1 rounded-lg transition-all ${
              filterResult === 'WIN' ? 'bg-purple-500/20 text-purple-300 font-bold border border-purple-500/30' : 'text-purple-300/60 hover:text-purple-200'
            }`}
          >
            Wins Only ({history.filter((h) => h.result === 'WIN').length})
          </button>
          <button
            onClick={() => setFilterResult('LOSS')}
            className={`px-3 py-1 rounded-lg transition-all ${
              filterResult === 'LOSS' ? 'bg-rose-500/20 text-rose-400 font-bold border border-rose-500/30' : 'text-purple-300/60 hover:text-purple-200'
            }`}
          >
            Losses ({history.filter((h) => h.result === 'LOSS').length})
          </button>
        </div>

        {/* Confidence Threshold Selector */}
        <div className="flex items-center gap-2 text-purple-300/60">
          <Filter className="w-4 h-4 text-purple-400" />
          <span>Confidence:</span>
          <select
            value={filterMinConfidence}
            onChange={(e) => setFilterMinConfidence(Number(e.target.value))}
            className="bg-[#0B061A] border border-purple-900/60 text-purple-200 rounded-lg px-2.5 py-1.5 focus:outline-none"
          >
            <option value={0}>All Confidence Tiers</option>
            <option value={85}>≥ 85% Confidence</option>
            <option value={90}>≥ 90% High Confidence</option>
          </select>
        </div>
      </div>

      {/* Predictions Table */}
      <div className="bg-[#120B28] rounded-2xl border border-purple-500/30 overflow-hidden shadow-xl">
        <div className="overflow-x-auto">
          <table className="w-full text-left font-mono text-xs">
            <thead className="bg-[#0B061A] text-purple-300/60 border-b border-purple-900/40 uppercase tracking-wider text-[11px]">
              <tr>
                <th className="p-4">Signal ID / Time</th>
                <th className="p-4">Direction</th>
                <th className="p-4">Target Price</th>
                <th className="p-4">Actual Close</th>
                <th className="p-4">Confidence</th>
                <th className="p-4">Market Edge</th>
                <th className="p-4">PnL Return</th>
                <th className="p-4 text-center">Result</th>
                <th className="p-4 text-right">Verifiable Hash</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-purple-900/30 text-purple-200">
              {filteredHistory.map((item) => {
                const isWin = item.result === 'WIN';
                return (
                  <tr key={item.id} className="hover:bg-purple-900/20 transition-colors">
                    <td className="p-4">
                      <div className="font-bold text-white">{item.id}</div>
                      <div className="text-[10px] text-purple-300/50">{item.timeString}</div>
                    </td>
                    <td className="p-4">
                      <span
                        className={`px-2 py-0.5 rounded text-[11px] font-extrabold ${
                          item.direction === 'YES'
                            ? 'bg-purple-500/20 text-purple-300 border border-purple-500/30'
                            : 'bg-rose-500/20 text-rose-400 border border-rose-500/30'
                        }`}
                      >
                        {item.direction}
                      </span>
                    </td>
                    <td className="p-4 font-bold text-purple-200">${item.targetPrice.toLocaleString()}</td>
                    <td className="p-4 font-bold text-white">${item.actualClose.toLocaleString()}</td>
                    <td className="p-4">
                      <span className="text-purple-300 font-bold">{item.confidence}%</span>
                    </td>
                    <td className="p-4 text-emerald-400 font-bold">+{item.edge}%</td>
                    <td className="p-4">
                      <span className={`font-bold ${item.pnlPct >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                        {item.pnlPct >= 0 ? '+' : ''}
                        {item.pnlPct}%
                      </span>
                    </td>
                    <td className="p-4 text-center">
                      {isWin ? (
                        <span className="inline-flex items-center gap-1 bg-purple-500/20 text-purple-300 px-2.5 py-1 rounded-full text-[10px] font-bold border border-purple-500/30">
                          <CheckCircle2 className="w-3.5 h-3.5 text-purple-400" /> WIN
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1 bg-rose-500/10 text-rose-400 px-2.5 py-1 rounded-full text-[10px] font-bold border border-rose-500/30">
                          <XCircle className="w-3.5 h-3.5" /> LOSS
                        </span>
                      )}
                    </td>
                    <td className="p-4 text-right">
                      <span className="text-purple-300/50 text-[10px] bg-[#0B061A] px-2 py-1 rounded border border-purple-900/40 inline-flex items-center gap-1 hover:text-purple-200 cursor-pointer">
                        {item.hash}
                        <ExternalLink className="w-3 h-3 text-purple-400" />
                      </span>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
